### ISSUE TITLE
eCommerce: Cloning a storefront causes impressive error

### ISSUE THREAD

**Issue by smclaughlin520** [equella/Equella#226]
Found in 6.4.r366
 
 Find a 6.3 STOREFRONT institution that works.
 Export it.
 Import it into 6.4.
 (So far everything works and there are no errors.)
 Clone the institution.
 It goes bezique.
 
 {code}
 09:35:11,614 16008b46-e294-471e-90cb-37ad5d3c0eec ERROR ProgressSection Error running clone operation
 java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Error in 113/5233.xml
  at com.tle.core.institution.impl.RunAsInstitutionImpl.execute(RunAsInstitutionImpl.java:58)
  at com.tle.core.institution.impl.RunAsInstitutionImpl.executeAsSystem(RunAsInstitutionImpl.java:77)
  at com.tle.core.services.impl.InstitutionImportServiceImpl.clone(InstitutionImportServiceImpl.java:281)
  at com.tle.core.security.impl.MethodSecurityInteceptor.invoke(MethodSecurityInteceptor.java:40)
  at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
  at com.tle.web.institution.section.CloneSection$1.run(CloneSection.java:113)
  at com.tle.web.institution.section.ProgressSection$ProgressRunnable.run(ProgressSection.java:249)
  at com.tle.web.institution.section.ProgressSection$1.doRun(ProgressSection.java:130)
  at com.tle.core.user.AuthenticatedThread.run(AuthenticatedThread.java:53)
  Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error in 113/5233.xml
  at com.tle.core.institution.impl.RunAsInstitutionImpl.execute(RunAsInstitutionImpl.java:58)
  at com.tle.core.institution.impl.RunAsInstitutionImpl.executeAsSystem(RunAsInstitutionImpl.java:77)
  at com.tle.core.institution.convert.AbstractMigratableConverter.clone(AbstractMigratableConverter.java:54)
  at com.tle.core.services.impl.InstitutionImportServiceImpl$2.run(InstitutionImportServiceImpl.java:295)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at com.tle.core.institution.impl.RunAsInstitutionImpl.execute(RunAsInstitutionImpl.java:54)
  ... 8 more
  Caused by: java.lang.RuntimeException: Error in 113/5233.xml
  at com.tle.core.institution.convert.ItemConverter$3.run(ItemConverter.java:264)
  at com.tle.core.institution.convert.AbstractMigratableConverter.doInTransaction(AbstractMigratableConverter.java:96)
  at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
  at com.tle.core.institution.convert.TransactionThreadPool$TransactionThread.doRun(TransactionThreadPool.java:95)
  ... 1 more
  Caused by: com.thoughtworks.xstream.converters.ConversionException: Could not find service for class 'com.tle.beans.entity.itemdef.ItemDefinition_$$_jvst6d0_4a' in entity registry! : Could not find service for class 'com.tle.beans.entity.itemdef.ItemDefinition_$$_jvst6d0_4a' in entity registry!
  ---- Debugging information ----
  message : Could not find service for class 'com.tle.beans.entity.itemdef.ItemDefinition_$$_jvst6d0_4a' in entity registry!
  cause-exception : java.lang.RuntimeException
  cause-message : Could not find service for class 'com.tle.beans.entity.itemdef.ItemDefinition_$$_jvst6d0_4a' in entity registry!
  class : com.tle.beans.item.Item
  required-type : com.tle.beans.entity.itemdef.ItemDefinition_$$_jvst6d0_4a
  path : /com.tle.beans.item.Item/itemDefinition
  line number : 38
  -------------------------------
  at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:89)
  at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:63)
  at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:76)
  at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:246)
  at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:218)

  at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:162)
  at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:82)
  at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:63)
  at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:76)
  at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:60)
  at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:137)
  at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:33)
  at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:926)
  at com.tle.core.institution.XmlHelper.readXmlFile(XmlHelper.java:113)
  at com.tle.core.institution.convert.ItemConverter$3.run(ItemConverter.java:192)
  ... 4 more
  Caused by: java.lang.RuntimeException: Could not find service for class 'com.tle.beans.entity.itemdef.ItemDefinition_$$_jvst6d0_4a' in entity registry!
  at com.tle.core.services.entity.BaseEntityXmlConverter.unmarshal(BaseEntityXmlConverter.java:57)
  at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:82)
  ... 18 more 
 {code}"

Issue Converted from original Equella JIRA

**Comment by cbeach47** [comment]
eCommerce was removed in 6.5.   Closing issue.
