### ISSUE TITLE
Error redrafting items that have been bulk removed from workflow

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#288]
Steps to reproduce:

- Setup a simple workflow containing one step task, and contribute an item to put it in that workflow.

- On the manage resources page choose the 'Remove from workflow' option for the item you added in step 1
- Redraft the item, upon save you will receive an error, and this corresponding error in the logs

14:01:26,385 ERROR [DefaultErrorSection] Error at http://charliedesk:8080/vanilla/access/runwizard.do :
java.lang.Error: Task History never exited for this task: task1   ID=5
	at com.tle.core.workflow.service.impl.TaskStatisticsServiceImpl.enterTask(TaskStatisticsServiceImpl.java:47)
	at com.tle.core.item.standard.operations.workflow.TaskOperation.enterTask(TaskOperation.java:470)
	at com.tle.core.item.standard.workflow.nodes.TaskStatus.enter(TaskStatus.java:129)
	at com.tle.core.item.standard.operations.workflow.TaskOperation.enter(TaskOperation.java:90)
	at com.tle.core.item.standard.operations.workflow.TaskOperation.enter(TaskOperation.java:67)
	at com.tle.core.item.standard.workflow.nodes.SerialStatus.update(SerialStatus.java:30)
	at com.tle.core.item.standard.workflow.nodes.SerialStatus.enter(SerialStatus.java:46)
	at com.tle.core.item.standard.operations.workflow.TaskOperation.enter(TaskOperation.java:90)
	at com.tle.core.item.standard.operations.workflow.TaskOperation.resetWorkflow(TaskOperation.java:166)
	at com.tle.core.item.standard.operations.workflow.SubmitOperation.execute(SubmitOperation.java:50)
	at com.tle.core.item.service.impl.ItemServiceImpl.execute(ItemServiceImpl.java:982)
	at com.tle.core.item.service.impl.ItemServiceImpl.execute(ItemServiceImpl.java:933)
	at com.tle.core.item.service.impl.ItemServiceImpl.runOperation(ItemServiceImpl.java:801)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
	at com.tle.core.item.service.impl.ItemServiceImpl.operation(ItemServiceImpl.java:1087)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
	at com.tle.web.wizard.impl.WizardServiceImpl.doSave(WizardServiceImpl.java:249)
	at com.tle.web.wizard.command.SaveDialog.save(SaveDialog.java:222)
	at sun.reflect.GeneratedMethodAccessor534.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.tle.web.sections.events.js.MethodInvocationEventGenerator$1.fireDirect(MethodInvocationEventGenerator.java:100)
	at com.tle.web.sections.events.AbstractDirectEvent.fire(AbstractDirectEvent.java:95)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:503)
	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:472)
	at com.tle.web.sections.generic.DefaultSectionInfo.processQueue(DefaultSectionInfo.java:465)
	at com.tle.web.sections.registry.SectionsControllerImpl.execute(SectionsControllerImpl.java:78)
	at com.tle.web.sections.registry.SectionsServlet.service(SectionsServlet.java:81)
	at com.tle.web.sections.equella.MultipartSectionsServlet.service(MultipartSectionsServlet.java:39)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:98)
	at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:102)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mrblippy** [comment]
Fixed: verified by manual test
