### ISSUE TITLE
Scripted tasks in parallel workflow steps don't play nicely with workflow tasks

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#293]
Steps to reproduce:

- Setup

 a workflow that looks like this
![workflow para](https://user-images.githubusercontent.com/4625498/29439997-e537ad82-8404-11e7-9e14-0dc79460db03.PNG)
- When an item is put into that workflow the moderator gets the following error in the logs when they try to moderate the task (t2)

java.lang.Error: Task History never exited for this task: t2 ID=4134     	at com.tle.core.workflow.service.impl.TaskStatisticsServiceImpl.enterTask(TaskStatisticsServiceImpl.java:47)     	at com.tle.core.item.standard.operations.workflow.TaskOperation$1.run(TaskOperation.java:480)     	at com.tle.core.item.standard.operations.SaveOperation.saveToRepository(SaveOperation.java:207)     	at com.tle.core.item.standard.operations.SaveOperation.execute(SaveOperation.java:131)     	at com.tle.core.item.service.impl.ItemServiceImpl.execute(ItemServiceImpl.java:982)     	at com.tle.core.item.service.impl.ItemServiceImpl.execute(ItemServiceImpl.java:933)     	at com.tle.core.item.service.impl.ItemServiceImpl.runOperation(ItemServiceImpl.java:801)     	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)     	at com.tle.core.item.service.impl.ItemServiceImpl.operation(ItemServiceImpl.java:1087)     	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)     	at com.tle.web.wizard.impl.WizardServiceImpl.doSave(WizardServiceImpl.java:249)     	at com.tle.web.wizard.command.SaveDialog.save(SaveDialog.java:222)     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)     	at java.lang.reflect.Method.invoke(Method.java:497)     	at com.tle.web.sections.events.js.MethodInvocationEventGenerator$1.fireDirect(MethodInvocationEventGenerator.java:100)     	at com.tle.web.sections.events.AbstractDirectEvent.fire(AbstractDirectEvent.java:95)     	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:503)     	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:472)     	at com.tle.web.sections.generic.DefaultSectionInfo.processQueue(DefaultSectionInfo.java:465)     	at com.tle.web.sections.registry.SectionsControllerImpl.execute(SectionsControllerImpl.java:78)     	at com.tle.web.sections.registry.SectionsServlet.service(SectionsServlet.java:81)     	at com.tle.web.sections.equella.MultipartSectionsServlet.service(MultipartSectionsServlet.java:39)     	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)     	at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:98)     	at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:102)     	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)     	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)     	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)     	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)     	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)     	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)     	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)     	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)     	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)     	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)     	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)     	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)     	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)     	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)     	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)     	at java.lang.Thread.run(Thread.java:745)

**Comment by mrblippy** [comment]
Fixed: verified with manual test
