### ISSUE TITLE
Inline file uploads: unzipping zip files with nested folders can fail

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#297]
Try uploading and unzipping this file into an item
[s.zip](https://github.com/equella/Equella/files/1233373/s.zip)

It will fail with the following error in the logs:
`com.tle.web.sections.ajax.exception.AjaxException: java.util.NoSuchElementException: key not found: 
    	at com.tle.web.sections.ajax.handler.StandardAjaxRenderContext.processEvent(StandardAjaxRenderContext.java:414) 
    	at com.tle.web.sections.events.StandardRenderEventContext.processEvent(StandardRenderEventContext.java:311) 
    	at com.tle.web.sections.SectionUtils.renderSectionResult(SectionUtils.java:764) 
    	at com.tle.web.sections.standard.dialog.AbstractDialog.getSelectedRenderer(AbstractDialog.java:394) 
    	at com.tle.web.sections.standard.dialog.AbstractDialog.renderHtml(AbstractDialog.java:235) 
    	at com.tle.web.sections.render.HtmlRendererListener.render(HtmlRendererListener.java:50) 
    	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:82) 
    	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:24) 
    	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:577) 
    	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:472) 
    	at com.tle.web.sections.generic.WrappedSectionInfo.processEvent(WrappedSectionInfo.java:245) 
    	at com.tle.web.sections.ajax.handler.StandardAjaxRenderContext.processEvent(StandardAjaxRenderContext.java:410) 
    	at com.tle.web.sections.events.StandardRenderEventContext.processEvent(StandardRenderEventContext.java:311) 
    	at com.tle.web.template.RenderTemplate.renderHtml(RenderTemplate.java:155) 
    	at com.tle.web.sections.render.HtmlRendererListener.render(HtmlRendererListener.java:50) 
    	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:82) 
    	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:24) 
    	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:577) 
    	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:472) 
    	at com.tle.web.sections.registry.SectionsControllerImpl.renderForward(SectionsControllerImpl.java:103) 
    	at com.tle.web.sections.registry.SectionsControllerImpl.execute(SectionsControllerImpl.java:79) 
    	at com.tle.web.sections.registry.SectionsServlet.service(SectionsServlet.java:81) 
    	at com.tle.web.sections.equella.MultipartSectionsServlet.service(MultipartSectionsServlet.java:39) 
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) 
    	at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:98) 
    	at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:102) 
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) 
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
    	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) 
    	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) 
    	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) 
    	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) 
    	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) 
    	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) 
    	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537) 
    	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085) 
    	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658) 
    	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222) 
    	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556) 
    	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513) 
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
    	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
    	at java.lang.Thread.run(Thread.java:745) 
    Caused by: java.util.NoSuchElementException: key not found: 
    	at scala.collection.MapLike$class.default(MapLike.scala:228) 
    	at scala.collection.AbstractMap.default(Map.scala:59) 
    	at scala.collection.MapLike$class.apply(MapLike.scala:141) 
    	at scala.collection.AbstractMap.apply(Map.scala:59) 
    	at com.tle.web.controls.universal.handlers.fileupload.details.FileEditDetails.com$tle$web$controls$universal$handlers$fileupload$details$FileEditDetails$$mkNodeChildren$1(FileEditDetails.scala:203) 
    	at com.tle.web.controls.universal.handlers.fileupload.details.FileEditDetails.prepareFileList(FileEditDetails.scala:205) 
    	at com.tle.web.controls.universal.handlers.fileupload.details.FileEditDetails.renderDetails(FileEditDetails.scala:194) 
    	at com.tle.web.controls.universal.handlers.FileUploadHandlerNew$AfterRegister.renderEditing(FileUploadHandlerNew.scala:378) 
    	at com.tle.web.controls.universal.handlers.FileUploadHandlerNew$AfterRegister.render(FileUploadHandlerNew.scala:327) 
    	at com.tle.web.controls.universal.handlers.FileUploadHandlerNew.render(FileUploadHandlerNew.scala:144) 
    	at com.tle.web.controls.universal.UniversalResourcesDialog.getDialogContents(UniversalResourcesDialog.java:244) 
    	at com.tle.web.sections.standard.dialog.AbstractDialog.prepareModel(AbstractDialog.java:267) 
    	at com.tle.web.sections.standard.AbstractRenderedComponent.renderHtml(AbstractRenderedComponent.java:251) 
    	at com.tle.web.sections.standard.dialog.AbstractDialog.renderHtml(AbstractDialog.java:237) 
    	at com.tle.web.sections.render.HtmlRendererListener.render(HtmlRendererListener.java:50) 
    	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:82) 
    	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:24) 
    	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:577) 
    	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:472) 
    	at com.tle.web.sections.generic.WrappedSectionInfo.processEvent(WrappedSectionInfo.java:245) 
    	at com.tle.web.sections.ajax.handler.StandardAjaxRenderContext.processEvent(StandardAjaxRenderContext.java:410) 
    	... 43 more`

**Comment by mrblippy** [comment]
Fixed: tested with manual tests
