### ISSUE TITLE
Inline file uploads: error when unzipping files on windows

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#302]
The following error occurs when you unzip a zip file, and select files to make visible
java.nio.file.FileSystemException: H:\equella64penopen\filestore\Staging\51\21458bab-584d-497c-86be-e8a2b4f4c2a9\Winter_Semester(2).zip: The process cannot access the file because it is being used by another process. 
     
    	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) 
    	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) 
    	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) 
    	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269) 
    	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103) 
    	at java.nio.file.Files.delete(Files.java:1126) 
    	at com.dytech.common.io.FileUtils.delete(FileUtils.java:121) 
    	at com.dytech.common.io.FileUtils.delete(FileUtils.java:60) 
    	at com.tle.common.filesystem.FileSystemHelper.rename(FileSystemHelper.java:138) 
    	at com.tle.core.services.impl.FileSystemServiceImpl.move(FileSystemServiceImpl.java:591) 
    	at com.tle.core.services.impl.FileSystemServiceImpl.move(FileSystemServiceImpl.java:597) 
    	at com.tle.web.controls.universal.FileStagingContext.moveFile(ControlContext.scala:74) 
    	at com.tle.web.controls.universal.handlers.FileUploadHandlerNew$AfterRegister$DetailsEditState.commit(FileUploadHandlerNew.scala:235) 
    	at com.tle.web.controls.universal.handlers.FileUploadHandlerNew$AfterRegister.editAttachment(FileUploadHandlerNew.scala:383) 
    	at com.tle.web.controls.universal.handlers.FileUploadHandlerNew.saveEdited(FileUploadHandlerNew.scala:149) 
    	at com.tle.web.controls.universal.UniversalResourcesDialog.saveClicked(UniversalResourcesDialog.java:391) 
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
    	at java.lang.reflect.Method.invoke(Method.java:497) 
    	at com.tle.web.sections.events.js.MethodInvocationEventGenerator$1.fireDirect(MethodInvocationEventGenerator.java:100) 
    	at com.tle.web.sections.events.AbstractDirectEvent.fire(AbstractDirectEvent.java:95) 
    	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:503) 
    	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:472) 
    	at com.tle.web.sections.generic.DefaultSectionInfo.processQueue(DefaultSectionInfo.java:465) 
    	at com.tle.web.sections.registry.SectionsControllerImpl.execute(SectionsControllerImpl.java:78) 
    	at com.tle.web.sections.registry.SectionsServlet.service(SectionsServlet.java:81) 
    	at com.tle.web.sections.equella.MultipartSectionsServlet.service(MultipartSectionsServlet.java:39) 
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) 
    	at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:98) 
    	at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:102) 
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) 
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 
    	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) 
    	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) 
    	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) 
    	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) 
    	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) 
    	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) 
    	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537) 
    	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085) 
    	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658) 
    	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222) 
    	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556) 
    	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513) 
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
    	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
    	at java.lang.Thread.run(Thread.java:745)

**Comment by mrblippy** [comment]
Fixed: tested with manual tests
