### ISSUE TITLE
Remote repos are busted

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#351]
I got the following error in the logs after attempting to search the attached z3950 repo. The other types of remote reps appear to busted in the same way

java.lang.NoClassDefFoundError: javax/xml/rpc/handler/soap/SOAPMessageContext 
    	at java.lang.ClassLoader.defineClass1(Native Method) 
    	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) 
    	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) 
    	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) 
    	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) 
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) 
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) 
    	at java.security.AccessController.doPrivileged(Native Method) 
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) 
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) 
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 
    	at java.lang.Class.getDeclaredMethods0(Native Method) 
    	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) 
    	at java.lang.Class.getDeclaredMethods(Class.java:1975) 
    	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:662) 
    	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:356) 
    	at com.tle.core.guice.DependencyAnalyzer.analyzeImplementation(DependencyAnalyzer.java:132) 
    	at com.tle.core.guice.DependencyAnalyzer.visit(DependencyAnalyzer.java:60) 
    	at com.tle.core.guice.DependencyAnalyzer.visit(DependencyAnalyzer.java:41) 
    	at com.google.inject.internal.UntargettedBindingImpl.acceptTargetVisitor(UntargettedBindingImpl.java:42) 
    	at com.tle.core.guice.ElementAnalyzer.visit(ElementAnalyzer.java:45) 
    	at com.tle.core.guice.ElementAnalyzer.visit(ElementAnalyzer.java:31) 
    	at com.google.inject.internal.BindingImpl.acceptVisitor(BindingImpl.java:93) 
    	at com.tle.core.guice.ExternalProviders.configure(ExternalProviders.java:50) 
    	at com.google.inject.AbstractModule.configure(AbstractModule.java:59) 
    	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223) 
    	at com.google.inject.spi.Elements.getElements(Elements.java:101) 
    	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133) 
    	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103) 
    	at com.google.inject.Guice.createInjector(Guice.java:95) 
    	at com.google.inject.Guice.createInjector(Guice.java:72) 
    	at com.google.inject.Guice.createInjector(Guice.java:62) 
    	at com.tle.core.guice.GuicePlugin$GuiceBeanLocator$InjectorCreation.doWork(GuicePlugin.java:295) 
    	at com.tle.core.guice.GuicePlugin$GuiceBeanLocator$InjectorCreation.doWork(GuicePlugin.java:272) 
    	at com.tle.core.plugins.AbstractBeanLocatorCallable.call(AbstractBeanLocatorCallable.java:76) 
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
    	at java.lang.Thread.run(Thread.java:745) 
    Caused by: java.lang.ClassNotFoundException: javax.xml.rpc.handler.soap.SOAPMessageContext 
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) 
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) 
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 
    	... 40 more
[Books - Libraries Australia.zip](https://github.com/equella/Equella/files/1370430/Books.-.Libraries.Australia.zip)

**Comment by mrblippy** [comment]
Fixed: Remote repositories are now workin'
