### ISSUE TITLE
Node failover on wizard fails

### ISSUE THREAD

**Issue by emcgarrahan** [equella/Equella#362]
Script: eqos-5311 

java.lang.RuntimeException: Couldn't find bean for type:Key[type=com.tle.web.wizard.WizardState, annotation=[none]]
    at com.tle.core.guice.ExternalProviders$ExternalProvider.get(ExternalProviders.java:95)
    at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
    at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
    at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
    at com.tle.web.wizard.WizardState.readResolve(WizardState.java:588)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1148)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2036)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
    at com.tle.core.plugins.SerialisedValue.getObject(SerialisedValue.java:72)
    at com.tle.core.services.user.impl.UserSessionServiceImpl.getAttributeFromSession(UserSessionServiceImpl.java:137)
    at com.tle.core.services.user.impl.UserSessionServiceImpl.getAttribute(UserSessionServiceImpl.java:79)
    at com.tle.web.wizard.impl.WizardServiceImpl.getFromSession(WizardServiceImpl.java:1419)
    at com.tle.web.wizard.section.RootWizardSection.beforeEvents(RootWizardSection.java:142)
    at com.tle.web.sections.events.BeforeEventsEvent.fire(BeforeEventsEvent.java:30)
    at com.tle.web.sections.events.BeforeEventsEvent.fire(BeforeEventsEvent.java:24)
    at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:561)
    at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:472)
    at com.tle.web.sections.generic.DefaultSectionInfo.fireBeforeEvents(DefaultSectionInfo.java:816)
    at com.tle.web.sections.registry.SectionsControllerImpl.execute(SectionsControllerImpl.java:77)
    at com.tle.web.sections.registry.SectionsServlet.service(SectionsServlet.java:81)
    at com.tle.web.sections.equella.MultipartSectionsServlet.service(MultipartSectionsServlet.java:39)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
    at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:98)
    at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:102)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
    at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:748)

**Comment by mrblippy** [comment]
Fixed, test case marked as passed
