### ISSUE TITLE
Task history getting exported with dodgy data

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#371]
Try to import the attached institution. It will fail with the following error:
java.lang.RuntimeException: java.lang.RuntimeException: Error in 10\12682.xml
	at com.tle.core.institution.impl.RunAsInstitutionImpl.execute(RunAsInstitutionImpl.java:58)
	at com.tle.core.institution.impl.RunAsInstitutionImpl.executeAsSystem(RunAsInstitutionImpl.java:77)
	at com.tle.core.institution.convert.service.impl.InstitutionImportServiceImpl.importInstitution(InstitutionImportServiceImpl.java:530)
	at com.tle.core.security.impl.MethodSecurityInteceptor.invoke(MethodSecurityInteceptor.java:40)
	at com.tle.web.institution.section.ImportSection$2.run(ImportSection.java:124)
	at com.tle.web.institution.section.ProgressSection$ProgressRunnable.run(ProgressSection.java:265)
	at com.tle.web.institution.section.ProgressSection$1.doRun(ProgressSection.java:146)
	at com.tle.common.usermanagement.user.AuthenticatedThread.run(AuthenticatedThread.java:54)
Caused by: java.lang.RuntimeException: Error in 10\12682.xml
	at com.tle.core.item.convert.ItemConverter$3.run(ItemConverter.java:271)
	at com.tle.core.institution.convert.AbstractMigratableConverter.doInTransaction(AbstractMigratableConverter.java:93)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
	at com.tle.core.institution.convert.TransactionThreadPool$TransactionThread.doRun(TransactionThreadPool.java:95)
	... 1 more
Caused by: com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : com.tle.common.workflow.node.WorkflowItem_$$_jvstbd5_28
[borked-institution.zip](https://github.com/equella/Equella/files/1400454/borked-institution.zip)

class               : com.tle.beans.TaskHistory
required-type       : com.tle.beans.TaskHistory
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /list/com.tle.beans.TaskHistory/task
line number         : 4
class[1]            : java.util.ArrayList
converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
version             : not available
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:73)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionConverter.java:98)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:91)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:85)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:80)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1230)
	at com.tle.core.institution.convert.XmlHelper.readXmlFile(XmlHelper.java:113)
	at com.tle.core.workflow.convert.TaskHistoryConverter.importExtras(TaskHistoryConverter.java:91)
	at com.tle.core.item.convert.ItemConverter.runExtras(ItemConverter.java:297)
	at com.tle.core.item.convert.ItemConverter$3.run(ItemConverter.java:260)
	... 4 more
Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: com.tle.common.workflow.node.WorkflowItem_$$_jvstbd5_28
	at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:81)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.XStream11XmlFriendlyMapper.realClass(XStream11XmlFriendlyMapper.java:38)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:71)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:47)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:424)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	... 23 more
[borked-institution.zip](https://github.com/equella/Equella/files/1400459/borked-institution.zip)

**Comment by doolse** [comment]
note for testing: the broken institution export will still be broken, so a new one must be exported.
