### ISSUE TITLE
SRU and SRW endpoints are busted

### ISSUE THREAD

**Issue by mrblippy** [equella/Equella#384]
I get the following error when accessing the srw or sru endpoints in equella. eg:
http://charliedesk:8092/vanillaext/srw/?operation=searchRetrieve&query=test
seems to happen in 6.4 as well

java.lang.NullPointerException     	at com.tle.web.endpoint.srw.EquellaSRWDatabase.getSchemaInfo(EquellaSRWDatabase.java:215)     	at ORG.oclc.os.SRW.SRWDatabase.makeExplainRecord(SRWDatabase.java:1267)     	at ORG.oclc.os.SRW.SRWDatabase.getExplainRecord(SRWDatabase.java:806)     	at ORG.oclc.os.SRW.SRWServletInfo.setSRWStuff(SRWServletInfo.java:453)     	at ORG.oclc.os.SRW.SRWServlet.processMethodRequest(SRWServlet.java:1154)     	at ORG.oclc.os.SRW.SRWServlet.doGet(SRWServlet.java:296)     	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)     	at org.apache.axis.transport.http.AxisServletBase.service(AxisServletBase.java:327)     	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)     	at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:98)     	at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:102)     	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)     	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)     	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)     	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)     	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)     	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)     	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)     	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)     	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)     	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)     	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)     	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)     	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)     	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)     	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)     	at java.lang.Thread.run(Thread.java:745)

**Comment by mrblippy** [comment]
Fixed
