### ISSUE TITLE
This ResultSet is closed.

### ISSUE THREAD

**Issue by timmartinez** [equella/Equella#402]
Did a fresh install on Windows server using JDK 8 152 and PostgreSQL 10.1. When first firing up the application I get a database error saying the result set is closed.

java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30100ms. 
    	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:602) 
    	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:195) 
    	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145) 
    	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85) 
    	at com.tle.core.hibernate.impl.DynamicDataSource.getConnection(DynamicDataSource.java:85) 
    	at com.tle.core.hibernate.HibernateFactory$DataSourceProvider.getConnection(HibernateFactory.java:152) 
    	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:113) 
    	at org.hibernate.cfg.Configuration.buildSettingsInternal(Configuration.java:2863) 
    	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2859) 
    	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1870) 
    	at com.tle.core.hibernate.HibernateFactory.getSessionFactory(HibernateFactory.java:114) 
    	at com.tle.core.migration.impl.HibernateMigrationService.getSessionFactory(HibernateMigrationService.java:83) 
    	at com.tle.core.migration.impl.HibernateMigrationService.checkSchemaForMigrations(HibernateMigrationService.java:103) 
    	at com.tle.core.migration.impl.MigrationGlobalTask.checkSystemSchema(MigrationGlobalTask.java:374) 
    	at com.tle.core.migration.impl.MigrationGlobalTask.init(MigrationGlobalTask.java:122) 
    	at com.tle.core.services.impl.AlwaysRunningTask.call(AlwaysRunningTask.java:38) 
    	at com.tle.core.services.impl.AlwaysRunningTask.call(AlwaysRunningTask.java:26) 
    	at com.tle.core.services.impl.LocalTaskServiceImpl$LocalTask.run(LocalTaskServiceImpl.java:597) 
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
    	at java.lang.Thread.run(Thread.java:748) 
    Caused by: com.zaxxer.hikari.pool.PoolBase$ConnectionSetupException: org.postgresql.util.PSQLException: This ResultSet is closed. 
    	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:418) 
    	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:361) 
    	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:199) 
    	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:444) 
    	at com.zaxxer.hikari.pool.HikariPool.access$200(HikariPool.java:71) 
    	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:631) 
    	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:617) 
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
    	at com.tle.core.hibernate.DataSourceServiceImpl$CreateDataSourceFunction$1$1.run(DataSourceServiceImpl.java:136) 
    Caused by: org.postgresql.util.PSQLException: This ResultSet is closed. 
    	at org.postgresql.jdbc2.AbstractJdbc2ResultSet.checkClosed(AbstractJdbc2ResultSet.java:2852) 
    	at org.postgresql.jdbc2.AbstractJdbc2ResultSet.setFetchSize(AbstractJdbc2ResultSet.java:1875) 
    	at org.postgresql.jdbc4.Jdbc4Statement.createResultSet(Jdbc4Statement.java:37) 
    	at org.postgresql.jdbc2.AbstractJdbc2Statement$StatementResultHandler.handleResultRows(AbstractJdbc2Statement.java:219) 
    	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1816) 
    	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) 
    	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:559) 
    	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403) 
    	at org.postgresql.jdbc2.AbstractJdbc2Connection.execSQLUpdate(AbstractJdbc2Connection.java:376) 
    	at org.postgresql.jdbc2.AbstractJdbc2Connection.getTransactionIsolation(AbstractJdbc2Connection.java:898) 
    	at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:444) 
    	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:403) 
    	... 10 more

**Comment by doolse** [comment]
The postgres drivers we were using didn't support posgres 10, so it's been upgraded.

**Comment by mrblippy** [comment]
Fixed
