### ISSUE TITLE
Build issue in master?

### ISSUE THREAD

**Issue by cbeach47** [equella/Equella#487]
Tried to build the latest code in master today (93957f21553fa82287b0ac37ffb650fc8b298a3d) and got a generic build failure.  Commit 924ab51c1a24f9f95150fe95501136f55bea4b04 builds successfully.  @doolse / @abidingotter - can you replicate the build issue?

```
[error] java.lang.RuntimeException: Running yarn script 'build' in dir /home/cbeach/repo-builder/Equella/Source/Plugins/Core/com.equella.core/js failed
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at Common$.runYarn(Common.scala:66)
[error] 	at $d0a994e360538378161f$.$anonfun$$sbtdef$1(/home/cbeach/repo-builder/Equella/Source/Plugins/Core/com.equella.core/build.sbt:93)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
...
```

**Comment by doolse** [comment]
Fixed it
