### ISSUE TITLE
Make number of item and attachment views available in real time

### ISSUE THREAD

**Issue by abidingotter** [equella/Equella#519]
Currently we can only determine how frequently an item or attachment is viewed by running reports against the audit log entry table.
This new feature will make the view count available directly on the item summary.  It will use the same logic as the audit logs (ie NONE, NORMAL or SMART)
A simple view count and last view date will be updated upon each view.  There may be concurrency / performance issues with multiple concurrent requests which we will need to consider.

**Comment by cbeach47** [comment]
:+1: 

Is the current plan to include the ability to sort by item views so users can find the most 'popular' items?

**Comment by mrblippy** [comment]
I get a nullpointer when importing an institution that contains Item View data

`java.lang.RuntimeException: java.lang.NullPointerException
	at com.tle.core.institution.impl.RunAsInstitutionImpl.execute(RunAsInstitutionImpl.java:74)
	at com.tle.core.institution.impl.RunAsInstitutionImpl.executeAsSystem(RunAsInstitutionImpl.java:93)
	at com.tle.core.institution.convert.service.impl.InstitutionImportServiceImpl.importInstitution(InstitutionImportServiceImpl.java:545)
	at com.tle.core.security.impl.MethodSecurityInteceptor.invoke(MethodSecurityInteceptor.java:56)
	at com.tle.core.security.impl.MethodSecurityInteceptor.invoke(MethodSecurityInteceptor.java:56)
	at com.tle.web.institution.section.ImportSection$2.run(ImportSection.java:124)
	at com.tle.web.institution.section.ProgressSection$ProgressRunnable.run(ProgressSection.java:265)
	at com.tle.web.institution.section.ProgressSection$1.doRun(ProgressSection.java:146)
	at com.tle.common.usermanagement.user.AuthenticatedThread.run(AuthenticatedThread.java:70)
Caused by: java.lang.NullPointerException
	at com.tle.core.item.convert.ViewsConverter.doImport(ViewsConverter.java:95)
	at com.tle.core.institution.convert.AbstractMigratableConverter$3.run(AbstractMigratableConverter.java:123)
	at com.tle.core.institution.convert.AbstractMigratableConverter.doInTransaction(AbstractMigratableConverter.java:109)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
	at com.tle.core.institution.convert.AbstractMigratableConverter.importIt(AbstractMigratableConverter.java:116)
	at com.tle.core.institution.convert.service.impl.InstitutionImportServiceImpl.doImport(InstitutionImportServiceImpl.java:570)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
	at com.tle.core.institution.convert.service.impl.InstitutionImportServiceImpl$4.run(InstitutionImportServiceImpl.java:550)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.tle.core.institution.impl.RunAsInstitutionImpl.execute(RunAsInstitutionImpl.java:70)
	... 8 more`

**Comment by abidingotter** [comment]
@cbeach47 Not at this stage.  It would need to re-index the item every time it was viewed, which would be very very time and resource expensive.

**Comment by abidingotter** [comment]
@mrblippy fixed NPE

**Comment by mrblippy** [comment]
Looks good now 👍
