### ISSUE TITLE
"could not initialize proxy - no Session" error when 2 attachment controls are restricted to different dynamic collections

### ISSUE THREAD

**Issue by nelson-edalex** [equella/Equella#612]
**Describe the bug**
Configuration:
- A collection that contains 2 attachment controls
- Both attachment controls are only allowed to have "EQUELLA resources"
- The controls are restricted to different dynamic collections

During the contribution, searching for EQUELLA resources occasionally returns "could not initialize proxy - no Session".
If the collection configuration is change such that both attachment controls are restricted to the same set of dynamic collections, there is no problem.

In addition, changing the collection does *NOT* result in the error immediately.  It will only come up after a minute or so.

**To Reproduce**
https://screencast.com/t/grQSpaGx
Also can test contribute the "Nelson test resource attachment" collection on https://au.equella.com/demo

**Expected behavior**
The "could not initialize proxy - no Session" error should not happen

**Screenshots**

**Platform:**
 - OpenEquella Version: 6.6r17

**Comment by mrblippy** [comment]
This is still happening in 6.6

Also, in 2018.2 the error is different, and is displayed in a less than ideal way in the new ui
![attachment control dynamic collections](https://user-images.githubusercontent.com/4625498/49846789-23097b80-fe21-11e8-867d-44d97b857720.PNG). The actual error in the logs is
` Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: com.tle.beans.entity.LanguageBundle.strings, no session or session was closed 
    	at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:383) 
    	at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationExceptionIfNotConnected(AbstractPersistentCollection.java:375) 
    	at org.hibernate.collection.AbstractPersistentCollection.readElementByIndex(AbstractPersistentCollection.java:176) 
    	at org.hibernate.collection.PersistentMap.get(PersistentMap.java:169) 
    	at com.tle.common.i18n.LangUtils.getClosestObjectForLocale(LangUtils.java:245) 
    	at com.tle.common.i18n.LangUtils.getString(LangUtils.java:93) 
    	at com.tle.common.i18n.LangUtils.getString(LangUtils.java:82) 
    	at com.tle.common.i18n.CurrentLocale$AbstractCurrentLocale.get(CurrentLocale.java:114) 
    	at com.tle.common.i18n.CurrentLocale.get(CurrentLocale.java:64) 
    	at com.tle.web.searching.SearchWhereModel.populateModel(SearchWhereModel.java:287) 
    	at com.tle.web.sections.standard.model.DynamicHtmlListModel.getListState(DynamicHtmlListModel.java:152) 
    	at com.tle.web.sections.standard.model.DynamicHtmlListModel.getOptions(DynamicHtmlListModel.java:49) 
    	at com.tle.web.sections.standard.MultiSelectionList.getOptions(MultiSelectionList.java:125) 
    	at com.tle.web.sections.standard.MultiSelectionList.prepareModel(MultiSelectionList.java:119) 
    	at com.tle.web.sections.standard.AbstractRenderedComponent.renderHtml(AbstractRenderedComponent.java:251) 
    	at com.tle.web.sections.render.HtmlRendererListener.render(HtmlRendererListener.java:50) 
    	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:82) 
    	at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:24) 
    	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:574) 
    	at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:469) 
    	at com.tle.web.sections.generic.WrappedSectionInfo.processEvent(WrappedSectionInfo.java:244) 
    	at com.tle.web.sections.SectionWriter.processEvent(SectionWriter.java:452) 
    	at com.tle.web.sections.equella.freemarker.ChooseRenderer.getSectionRenderable(ChooseRenderer.java:101) 
    	... 135 more`

**Comment by mrblippy** [comment]
Verified in 2018.2 and 6.6
