### ISSUE TITLE
Head of develop not building

### ISSUE THREAD

**Issue by cbeach47** [equella/Equella#807]
**Describe the bug**
The head of develop (commit `https://github.com/equella/Equella/commit/2a3cbf12985f3a050cd723020e90ea529fabc50a`) is not building on my local. 

@edalex-ian - did the Edalex team add any new dependencies?  It's failing to find the `warning` module.  I see the README now states we need node and npm, which I have (node = v10.13.0 , npm = v6.4.1).  

**To Reproduce**
1. Clone the Equella repo
2. Checkout the develop branch
3. Run `sbt installerZip`

**Expected behavior**
Equella should build.  :)

**Stacktrace**
```
/home/cbeach/repo/Equella/Source/Plugins/Core/com.equella.core/js/node_modules/@material-ui/core/styles/colorManipulator.js:19:46: Cannot resolve dependency 'warning'
  17 | exports.lighten = lighten;
  18 | 
> 19 | var _warning = _interopRequireDefault(require("warning"));
     |                                              ^
  20 | 
  21 | /* eslint-disable no-use-before-define */
  22 | 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openequella-web@ build:bundles: `run-s bundleps && cross-env-shell parcel build --public-url=./reactjs/ --out-dir=${npm_package_config_dist} entrybuild/*.html entrybuild/uploadlist.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openequella-web@ build:bundles script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cbeach/.npm/_logs/2019-04-02T23_36_12_842Z-debug.log
ERROR: "build:bundles" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openequella-web@ build: `npm-run-all build:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openequella-web@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cbeach/.npm/_logs/2019-04-02T23_36_12_863Z-debug.log
[error] java.lang.RuntimeException: Running node script 'build' in dir /home/cbeach/repo/Equella/Source/Plugins/Core/com.equella.core/js failed
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at Common$.nodeScript(Common.scala:69)
[error] 	at $019f1122def8fcd5155b$.$anonfun$$sbtdef$1(/home/cbeach/repo/Equella/Source/Plugins/Core/com.equella.core/build.sbt:128)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (com_equella_core / buildJS) Running node script 'build' in dir /home/cbeach/repo/Equella/Source/Plugins/Core/com.equella.core/js failed
[error] Total time: 250 s, completed Apr 2, 2019 6:36:17 PM
```

**Platform:**
- OpenEquella Version: 2019.1 Alpha
- OS: Ubuntu 16.04

**Comment by mrblippy** [comment]
Hi Chris, I ran into this problem yesterday. Try running npm run clean

**Comment by cbeach47** [comment]
npm is complaining that it can't find a 'clean' script...  How is the clean script defined in your package.json?

I tried `rm -rf node_modules` and rebuilding the installer - same error.  I also tried `npm install warning` and rebuilding the installer - same error.

**Comment by cbeach47** [comment]
I ended up removing `psc-package` from my path (after remembering that `psc-package` is no longer a prereq to building oE), and removed `node_modules package-lock.json Source/Plugins/Core/com.equella.core/js/package-lock.json Source/Plugins/Core/com.equella.core/swaggerui/package-lock.json`.  

After restarting my laptop, oE finally built.
